build_script:
    # TODO: remove the line below once the AppVeyor installation includes a
    # newer version of pacman that can perform core updates
    - C:\msys64\usr\bin\pacman --noconfirm --sync --refresh --refresh pacman

    # Git is required but currently not part of AppVeyor installation
    - C:\msys64\usr\bin\pacman --noconfirm --sync --refresh --refresh git

    - C:\msys64\usr\bin\pacman --noconfirm --sync --refresh --refresh --sysupgrade --sysupgrade
    - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/ci-build.sh"

artifacts:
    - path: artifacts\*
